"""sync schema

Revision ID: faa6f74cbb59
Revises: 
Create Date: 2026-05-10 14:39:41.057745

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'faa6f74cbb59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adjunto', schema=None) as batch_op:
        batch_op.alter_column('ruta_archivo',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('correos_destinos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('estado', schema=None) as batch_op:
        batch_op.alter_column('nombre_estado',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('color',
               existing_type=sa.TEXT(),
               type_=sa.String(length=32),
               existing_nullable=True)

    with op.batch_alter_table('roll', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre_roll'])

    with op.batch_alter_table('sprint_burndown', schema=None) as batch_op:
        batch_op.alter_column('idsprint',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_sprint_burndown_sprint'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sprint', ['idsprint'], ['idsprint'])

    with op.batch_alter_table('sprint_retro', schema=None) as batch_op:
        batch_op.alter_column('idsprint',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('fk_sprint_retro_sprint'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sprint', ['idsprint'], ['idsprint'])

    with op.batch_alter_table('sprint_rol', schema=None) as batch_op:
        batch_op.alter_column('idsprint',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('idusuario',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('rol',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_sprint_rol_sprint'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'sprint', ['idsprint'], ['idsprint'])
        batch_op.create_foreign_key(None, 'usuario', ['idusuario'], ['idusuario'])

    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.alter_column('prioridad_scrum',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('tarea_dependencia', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tarea_dependencia_idtarea_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('tarea_dependencia_idpredecesor_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'tarea', ['idpredecesor'], ['idtarea'])
        batch_op.create_foreign_key(None, 'tarea', ['idtarea'], ['idtarea'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tarea_dependencia', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tarea_dependencia_idpredecesor_fkey'), 'tarea', ['idpredecesor'], ['idtarea'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('tarea_dependencia_idtarea_fkey'), 'tarea', ['idtarea'], ['idtarea'], ondelete='CASCADE')

    with op.batch_alter_table('tarea', schema=None) as batch_op:
        batch_op.alter_column('prioridad_scrum',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)

    with op.batch_alter_table('sprint_rol', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sprint_rol_sprint'), 'sprint', ['idsprint'], ['idsprint'], ondelete='CASCADE')
        batch_op.alter_column('rol',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('idusuario',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('idsprint',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sprint_retro', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sprint_retro_sprint'), 'sprint', ['idsprint'], ['idsprint'], ondelete='CASCADE')
        batch_op.alter_column('idsprint',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('sprint_burndown', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_sprint_burndown_sprint'), 'sprint', ['idsprint'], ['idsprint'], ondelete='CASCADE')
        batch_op.alter_column('idsprint',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('roll', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('estado', schema=None) as batch_op:
        batch_op.alter_column('color',
               existing_type=sa.String(length=32),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nombre_estado',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('correos_destinos', schema=None) as batch_op:
        batch_op.alter_column('creado_en',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('adjunto', schema=None) as batch_op:
        batch_op.alter_column('ruta_archivo',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###
